# Generated by Django 4.2.4 on 2024-01-13 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_poi_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poi',
            unique_together={('user', 'point')},
        ),
    ]
