# Generated by Django 4.2.4 on 2024-01-13 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_poi_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poi',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='poi',
            unique_together={('user', 'name')},
        ),
    ]
